version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: ojanjon/loyaltygoo-landing:latest
    volumes:
      - ./:/var/www/html
    networks:
      - laravel

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

networks:
  laravel:

